name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Build and Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build

      - name: Generate changelog
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          python3 utils/changelog_generator.py --tag "${CURRENT_TAG}" --latest "${PREVIOUS_TAG}"

      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release create "$TAG_NAME" -F CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
